### ISSUE TITLE
Is there any docs for CPU-MEM cost model? I wonder the advantages & disadvantanges.

### ISSUE THREAD

**Issue by cy-zheng** [Huawei-PaaS/firmament#40]

**Comment by deepak-vij** [comment]
See here. https://kubernetes.io/docs/concepts/extend-kubernetes/poseidon-firmament-alternate-scheduler/

**Comment by cy-zheng** [comment]
One more question: 
Is there any plan to achieve data locality cost model, like Quincy?

**Comment by deepak-vij** [comment]
Not at this time. We are currently working on the complex Gang Scheduling, including proportions, fairness etc. You are welcome to work on it, if you would like.

**Comment by cy-zheng** [comment]
OK, thanks!

**Comment by chauncey-77** [comment]
> See here. https://kubernetes.io/docs/concepts/extend-kubernetes/poseidon-firmament-alternate-scheduler/

The link is broken now.

**Comment by deepak-vij** [comment]
@anvithks

**Comment by anvithks** [comment]
> > See here. https://kubernetes.io/docs/concepts/extend-kubernetes/poseidon-firmament-alternate-scheduler/
> 
> The link is broken now.

@deepak-vij The docs are based on Kubernetes version.

The documentation is available in the K8S v15 docs. 
Here you go
[https://v1-15.docs.kubernetes.io/docs/concepts/extend-kubernetes/poseidon-firmament-alternate-scheduler/](https://v1-15.docs.kubernetes.io/docs/concepts/extend-kubernetes/poseidon-firmament-alternate-scheduler/)

**Comment by deepak-vij** [comment]
@anvithks , all the links on the Poseidon blog are broken now for some reason. Someone pointed it out. Can we fix it. thanks.

**Comment by deepak-vij** [comment]
@anvithks, see the following link to the blog.

https://kubernetes.io/blog/2019/02/06/poseidon-firmament-scheduler-flow-network-graph-based-scheduler/

**Comment by anvithks** [comment]
> @anvithks, see the following link to the blog.
> 
> https://kubernetes.io/blog/2019/02/06/poseidon-firmament-scheduler-flow-network-graph-based-scheduler/

I will see if I can update these when I have some free time.

The links just need to be updated to the v1. 15 docs linked above.

**Comment by deepak-vij** [comment]
@anvithks, thanks. Let me know when done so that I can let the community member know who wants to look at the docs. Thanks.

**Comment by anvithks** [comment]
> @anvithks, thanks. Let me know when done so that I can let the community member know who wants to look at the docs. Thanks.

The docs are available [here](https://v1-15.docs.kubernetes.io/docs/concepts/extend-kubernetes/poseidon-firmament-alternate-scheduler/) now.
No need to wait.

**Comment by deepak-vij** [comment]
@chauncey-77, you can see the docs as @anvithks mentioned.

@chauncey-77, I will also publish the Google Doc for the CPU/Mem design on github.

**Comment by chauncey-77** [comment]
It's very kind of you, thanks again!

**Comment by chauncey-77** [comment]
> @chauncey-77, you can see the docs as @anvithks mentioned.
> 
> @chauncey-77, I will also publish the Google Doc for the CPU/Mem design on github.

Hi, has the Coogle Doc for the CPU/Mem design been published on github?  If it has, please share the link, thanks!

**Comment by deepak-vij** [comment]
Sorry, I have been quite busy and ongoing holidays stuff. I am still trying to dig out information we put together at the time. Have not been able to find it yet. I will publish something when ready. In the meanwhile, code is quite self explanatory w.r.t. multi-dimensional CPU/Mem based cost model.

**Comment by chauncey-77** [comment]
> Sorry, I have been quite busy and ongoing holidays stuff. I am still trying to dig out information we put together at the time. Have not been able to find it yet. I will publish something when ready. In the meanwhile, code is quite self explanatory w.r.t. multi-dimensional CPU/Mem based cost model.

Yes I am reading the function in cpu_cost_model.h/cc, and I have figured out most of them. But at the same time I also have many questions. For example, I still can't understand the construction process of flow graph, i.e., how to generate the flow graph according to the CPU/Mem scheduling strategy. The cpu_cost_model involves some types of graph nodes, such as EquivClass, task, UnSceduledAgg, resource and sink, but I don’t figure out how these nodes form the flow graph. When comparing this graph construction function and those mentioned in the Firmament paper, I think they are different. So is there an example to understand the flow graph construction process like the Firmament paper do?

**Comment by deepak-vij** [comment]
Yes, graph construction is different as we are dealing with complex multi-dimensional cost model. Firmament paper does not get into that. Give me some time, I will provide details.

**Comment by chauncey-77** [comment]
> Yes, graph construction is different as we are dealing with complex multi-dimensional cost model. Firmament paper does not get into that. Give me some time, I will provide details.

Oh this is awesome, I am very much looking forward to it.
