### ISSUE TITLE
Hardware recommendation

### ISSUE THREAD

**Issue by cy-zheng** [Huawei-PaaS/firmament#41]
Is there a hardware recommendation for firmament scbeduler deployment?

**Comment by shivramsrivastava** [comment]
@cy-zheng We don't have any specific hardware recommendation. 
You can find the system requirements [here](https://github.com/Huawei-PaaS/firmament#system-requirements).
If you are looking for some thing like Arm or Rasberrypi type of hardwares we haven't tried yet :-( .
